




class EventClass:
    """This class is will be generated by the code for an event. It contains the event data"""
    def __init__(self, event_name:str, event_data, widget_id:int, storyboard_class) -> None:
        self.event_name : str = event_name
        self.event_data = event_data
        self.widget_id : int = widget_id
        self.storyboard_class = storyboard_class
    
    def __str__(self) -> str:
        return str(self.event_data)
    
    def __dict__ (self):
        return {
            "event_name": self.event_name,
            "event_data": self.event_data,
            "widget_id": self.widget_id
        }